import datetime
import uuid
from dataclasses import field


#this is for the spiders that are going to scrape the websites so that they don't scrape random things

class RawArticle:
    def __init__(self, source, url,  title, author,content, tags, published_at):

        #fields come first
        self.source = source # the source is hacker news, wikipedia or arxiv
        self.url = url #the url from which the data was pulled from
        self.title = title #title of the article
        self.author = author #author who wrote
        self.content = content #content of the article
        self.tags = tags if tags is not None else [] #categories and stuff, basically recommendation signals, by default should be empty list
        self.published_at = published_at

        #optional and autogenerated come next
        self.id = str(uuid.uuid4()) # every post scraped needs to have an id
        self.scraped_at = datetime.datetime.now()  # date at which the article was pulled


class StreamEvent:
    def __init__(self, event_type, article_id, minio_path, source):
        self.event_type = event_type
        self.article_id = article_id
        self.minio_path = minio_path
        self.source = source

        self.timestamp = str(datetime.datetime.now())

